# Generated by Django 5.2.8 on 2025-12-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
