# Generated by Django 5.2.8 on 2025-12-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissionInquiry',
        ),
        migrations.DeleteModel(
            name='AdmissionsRequest',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='ContactRequest',
        ),
    ]
